### PR TITLE
[MJDEPS-23] The parameter multiRelease should have a user property so that you can set it from the command line

### PR DESCRIPTION
**Pull request by NennoA**
Mapping parameter multielease to property jdeps.multiRelease

### CODE REVIEW

**Comment by eolivelli** [comment]
Le'ts wait for CI
https://builds.apache.org/job/maven-box/job/maven-jdeps-plugin/job/MJDEPS-23/

**Comment by eolivelli** [comment]
Merged to master
thank you @NennoA !

**Comment by NennoA** [comment]
I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

**Comment by eolivelli** [comment]
thank you @NennoA 
may I add you to the pom.xml as contributor ?

**Comment by NennoA** [comment]
Yes, thank you

**Comment by eolivelli** [comment]
Here you are https://github.com/apache/maven-jdeps-plugin/blob/9f80c9873cb1035a549555a83264ff8f4e268464/pom.xml#L72

**Comment by jira-importer** [comment]
Resolve #33

**Pull request closed without merging**
