### PR TITLE
[MJDEPS-16] Setup 'jdeps' goal alongside with 'jdkinternals'

### PR DESCRIPTION
**Pull request by andretadeu**
Hello, people!

In this PR, I setup 'jdeps' goal alongside with 'jdkinternals' to check if we should set -jdkinternals paramater. In addition, I had to append 'module-info.class' whenever jdeps is using against a modularized project or not, except when you should do a 'jdeps -m <module> <target>.' Furthermore, I had to fix some tests that were too reliant on the output format of 'jdeps'.

Thanks,

### CODE REVIEW

**Comment by rfscholte** [comment]
I'm a bit confused: MJDEPS-16 is about extending the existing goals by scanning the dependencies for internal JDK usage too (by default). So why a new goal? That would be a new MJDEPS issue.
It seems to me these PRs are much bigger than MJDEPS-16

**Comment by rfscholte** [comment]
First let's have a look at https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven-jdeps-plugin/job/master/
For some reason Jan 10 all was good, but now the 2 Linux + Java8 jobs are failing while the rest seems fine. This needs to get back to green before we pick up any issue.
The request from the user is different: now only the `target/classes` are scanned for usage of jdk internals. Instead he also wants to scan all dependencies by default, because that will confirm that this set of jars is Java 9 proof as a whole.

**Comment by andretadeu** [comment]
It seems reasonable. In first place, I'll fix these errors. Regarding to the Maven task, I'll open a new issue for that, as for the other issues.

**Comment by andretadeu** [comment]
@rfscholte The issues [MJDEPS-18](https://issues.apache.org/jira/browse/MJDEPS-18), [MJDEPS-19](https://issues.apache.org/jira/browse/MJDEPS-19), [MJDEPS-20](https://issues.apache.org/jira/browse/MJDEPS-20), and [MJDEPS-21](https://issues.apache.org/jira/browse/MJDEPS-21) were created.

**Comment by rfscholte** [comment]
I'm going to close this one in favor of #4 for MJDEPS-16

**Pull request closed without merging**
